### ISSUE TITLE
dd-trace calls in separate thread do not fail test

### ISSUE THREAD

**Issue by firezdog** [miketheman/pytest-socket#168]
https://github.com/DataDog/dd-trace-py/issues/4179

Sometimes we get dd-trace errors in a thread when running pytest.  I'm not sure what the cause is or if using a flag disabled this behavior, but what's disturbing to me is that I see the exception printed when running the tests and yet the tests do not fail.  Shouldn't any socket call regardless of whether it occurs as part of the test itself or in some thread that gets started with the tests cause tests to fail?  It does seem like the actual socket call is getting blocked, but the call should cause the tests to fail as well.

This is the pytest warning output:

```
test/<redacted>
  .../code/<redacted>/venv/lib/python3.10/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread ddtrace.internal.writer:AgentWriter
  
  Traceback (most recent call last):
    File ".../.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "...<redacted>/venv/lib/python3.10/site-packages/ddtrace/internal/periodic.py", line 70, in run
      self._target()
    File "...<redacted>/venv/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 583, in periodic
      self.flush_queue(raise_exc=False)
    File "...<redacted>/venv/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 559, in flush_queue
      self._retry_upload(self._send_payload, encoded, n_traces)
    File "...<redacted>/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 406, in __call__
      do = self.iter(retry_state=retry_state)
    File "...<redacted>/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 351, in iter
      return fut.result()
    File ".../.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/_base.py", line 451, in result
      return self.__get_result()
    File ".../.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
      raise self._exception
    File "...<redacted>/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 409, in __call__
      result = fn(*args, **kwargs)
    File "...<redacted>/venv/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 446, in _send_payload
      response = self._put(payload, headers)
    File "...<redacted>/venv/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 398, in _put
      self._conn.request("PUT", self._endpoint, data, headers)
    File ".../.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1282, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File ".../.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1328, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File ".../.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1277, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File ".../.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1037, in _send_output
      self.send(msg)
    File ".../.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 975, in send
      self.connect()
    File ".../.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 941, in connect
      self.sock = self._create_connection(
    File ".../.pyenv/versions/3.10.6/lib/python3.10/socket.py", line 828, in create_connection
      sock = socket(af, socktype, proto)
    File "...<redacted>/venv/lib/python3.10/site-packages/pytest_socket.py", line 80, in __new__
      raise SocketBlockedError()
  pytest_socket.SocketBlockedError: A test tried to use socket.socket.
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

**Comment by firezdog** [comment]
I've tried to catch this with the following:

```
filterwarnings =
    error::pytest.PytestUnhandledThreadExceptionWarning
    error:::pytest_socket.SocketBlockedError
```

Even then the test doesn't always fail.

**Comment by miketheman** [comment]
@firezdog Thanks for reporting! It's not super clear if this is a behavior that `pytest-socket` is responsible for, or rather how the `ddtrace` pytest plugin operates.
As can be seen in the output you shared, `pytest-socket` operates correctly by blocking the socket access with a `raise`. The call from  `ddtrace` uses a thread (`from ddtrace/internal/periodic.py", line 70, in run`), and the thread died due to being blocked, thus the warning - so all that sounds right.

Is the issue that a warning shows up at all, or that the test suite **doesn't** fail when the socket is blocked for the tracer?

**Comment by firezdog** [comment]
Hi Mike -- yeah I expected that the test suite would fail b/c of the socket call.  Is it b/c this happens in a thread operating outside of the test suite or something?

**Comment by firezdog** [comment]
@miketheman was this sufficient information or did you need anything else?  If this isn't an issue feel free to close, I'm just curious as to whether this would be a situation where the test suite should fail in your mind.

**Comment by miketheman** [comment]
@firezdog I don't think I know enough about how to reproduce this to answer your question.
The `PytestUnhandledThreadExceptionWarning` is raised due to `pytest-socket` doing its job blocking an outbound call - which is the desired outcome.

Whether the test case should fail or not due to a dependency making a remote call in a thread is seems like something pytest itself thinks is only cause for warning seems like the job for `filterwarnings` like you've specified.
As to whether it should happen all the time, I can't say - since that's up to the behavior of `ddtrace` and when it uses the `ddtrace.internal.writer:AgentWriter` to `flush_queue()` during your test run.

If you think this should still should fail regardless of the pytest-provided warning, then please provide a more concrete reproducible example to test against.
