### ISSUE TITLE
vscode-python version 2023.20.0 breaks disable_socket expected behavior

### ISSUE THREAD

**Issue by JSaja** [miketheman/pytest-socket#268]
I have been using `disable_socket` for a while now on a repo of mine via `conftest.py`. I have it set up verbatim as per the docs.
```
from pytest_socket import disable_socket

def pytest_runtest_setup():
    disable_socket()
```

It seems to have been working perfectly up until recently when the new Python Vscode extension `2023.20.0` changed the behavior of `send_post_request` to raise a new error `VsCodePytestError` whenever there is an exception on a socket connect.

Previous behavior - exception would fall through, allowing tests to still pass. [Link to this 2023.18.0 version](https://github.com/microsoft/vscode-python/blob/release/2023.18/pythonFiles/vscode_pytest/__init__.py#L690-L696)
```
    if __socket is None:
        try:
            __socket = socket_manager.SocketManager(addr)
            __socket.connect()
        except Exception as error:
            print(f"Plugin error connection error[vscode-pytest]: {error}")
            __socket = None

```

New behavior - `VsCodePytestError` is raised, causing tests to fail. [Link to this 2023.20.0 version](https://github.com/microsoft/vscode-python/blob/release/2023.20/pythonFiles/vscode_pytest/__init__.py#L718-L732)
```
    if __socket is None:
        try:
            __socket = socket_manager.SocketManager(addr)
            __socket.connect()
        except Exception as error:
            error_msg = f"Error attempting to connect to extension communication socket[vscode-pytest]: {error}"
            print(error_msg, file=sys.stderr)
            print(
                "If you are on a Windows machine, this error may be occurring if any of your tests clear environment variables"
                " as they are required to communicate with the extension. Please reference https://docs.pytest.org/en/stable/how-to/monkeypatch.html#monkeypatching-environment-variables"
                "for the correct way to clear environment variables during testing.\n",
                file=sys.stderr,
            )
            __socket = None
            raise VSCodePytestError(error_msg)
```

Removing the new line `raise VSCodePytestError(error_msg)` seems to allow tests to function as before. Full stack trace below
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/root/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/vscode_pytest/__init__.py", line 697, in send_post_request
INTERNALERROR>     __socket.connect()
INTERNALERROR>   File "/root/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/testing_tools/socket_manager.py", line 32, in connect
INTERNALERROR>     self.socket = socket.socket(
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pytest_socket.py", line 80, in __new__
INTERNALERROR>     raise SocketBlockedError()
INTERNALERROR> pytest_socket.SocketBlockedError: A test tried to use socket.socket.
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/terminal.py", line 574, in pytest_runtest_logreport
INTERNALERROR>     *self.config.hook.pytest_report_teststatus(report=rep, config=self.config)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 62, in _multicall
INTERNALERROR>     next(wrapper_gen)  # first yield
INTERNALERROR>   File "/root/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/vscode_pytest/__init__.py", line 229, in pytest_report_teststatus
INTERNALERROR>     execution_post(
INTERNALERROR>   File "/root/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/vscode_pytest/__init__.py", line 636, in execution_post
INTERNALERROR>     send_post_request(payload)
INTERNALERROR>   File "/root/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/vscode_pytest/__init__.py", line 708, in send_post_request
INTERNALERROR>     raise VSCodePytestError(error_msg)
INTERNALERROR> vscode_pytest.VSCodePytestError: Error attempting to connect to extension communication socket[vscode-pytest]: A test tried to use socket.socket.
```

**Comment by miketheman** [comment]
@JSaja Thanks for the report! Considering the change is located over on the extension repo, wouldn't this be better reported to them instead?

**Comment by JSaja** [comment]
Sorry for the late reply - yes that sounds like the better place to report it. Just wanted to make sure it was visible :)
