### ISSUE TITLE
Issues with asyncio

### ISSUE THREAD

**Issue by jdb8** [miketheman/pytest-socket#7]
Just stumbled upon this repo today, looks really interesting! I was testing it out on some py36 code which uses `asyncio`, and realised calling `asyncio.get_event_loop()` internally relies on `socket.socket`:

```python
>>> asyncio.get_event_loop()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/events.py", line 671, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 580, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "/usr/lib/python3.6/asyncio/events.py", line 598, in new_event_loop
    return self._loop_factory()
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 56, in __init__
    super().__init__(selector)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 67, in __init__
    self._make_self_pipe()
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 129, in _make_self_pipe
    self._ssock, self._csock = self._socketpair()
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 60, in _socketpair
    return socket.socketpair()
  File "/usr/lib/python3.6/socket.py", line 489, in socketpair
    a = socket(family, type, proto, a.detach())
...
```

in addition, I saw `AttributeError`s like this when running on real code (likely related to the above?):

```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 511, in __del__
    self.close()
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 63, in close
    super().close()
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 110, in close
    self._close_self_pipe()
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 120, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
```

Given the intention of this plugin is to block *all* sockets, I can understand why this happens. But I'd like the ability to block external network requests yet still allow python to internally use things like asyncio. Any ideas if that's fixable here, or if it's worth persuing another solution?

**Comment by miketheman** [comment]
Hi there! It seems almost identical to #6 - had you read that issue? There's a lot of context and the discussion of potential solutions.

**Comment by miketheman** [comment]
Closing, as we've got a [patch](https://github.com/miketheman/pytest-socket/pull/54) that enables using the plugin with asyncio, using an option. Will be releasing soon!
